### ISSUE TITLE
It is possible to display only lines with difference in diff report

### ISSUE THREAD

**Issue by koanya** [austincheney/prettydiff#44]
Hello,

I would like to display in the diff report only lines with difference and not all the document. Is there an option for that (I loook for but find nothing) ?

Thank you

**Comment by austincheney** [comment]
In the HTML tool there is an option called *Context size (optional)*. Just provide a value of 0. This option is named *context* in the API (if you are using Pretty Diff outside the web tool). Please let me know if this fails to help you!

**Comment by koanya** [comment]
It works. Thank you very much ;)
